sudo dnf install firefox \
    bspwm \
    kitty \
    xterm \
    neovim \
    thunar \
    compton \
    feh \
    sxhkd \
    light \
    atop \
    htop \
    pandoc \
    zathura \
    zathura-pdf-mupdf \
    zathura-cb \
    zathura-bash-completion \
    zathura-plugins-all \
    chromium \
    qutebrowser \
    copyq \
    flameshot \
    clang-tools-extra \
    zsh \
    vim \
    rofi \
    redshift \
    stalonetray \
    starship \
    redshift-gtk \
    licxcb-devel \
    libXft-devel \
    xdotool \
    wmctrl \
    fontawesome-fonts \
    acpitool \
    intel-media-driver \
    intel-gpu-tools \
    lshw \
    okular \
    pip \
    xrandr \
    wmctrl \
    fira-code-fonts \
    yt-dlp \
    gimp \
    boxes \
    neofetch \
    cmatrix \
    ranger \
    emacs \
    mediainfo \
    imv \
    cargo \
    ncurses-devel \
    figlet \
    qt5-qtbase-devel qt5-qtbase-static qt5-qt3d-devel harfbuzz-devel \ # sioyek
