#!/usr/bin/sh

width=$(xrandr | grep '*' | awk '{print $1}')
    # TODO

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a stalonetray state=floating
bspc rule -a copyq state=floating \
    center=true
bspc rule -a Zathura state=tiled \
    desktop='^1'

bash autostart
pgrep bspswallow || bspswallow &
